name: hulunkan_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - torch==2.5.1
      - torchvision==0.20.1
      - faster-coco-eval>=1.6.7
      - ultralytics==8.3.63
      - PyYAML
      - tensorboard
      - scipy
      - calflops
      - transformers
      - onnxruntime
      - tensorrt
      - opencv-python
      - pycocotools
      - numpy
      - pillow