__include__: [
  '../detrv4_configs/hulunkan_detection.yml',
  '../detrv4_configs/runtime.yml',
  '../detrv4_configs/dataloader.yml',
  '../detrv4_configs/optimizer.yml',
  '../detrv4_configs/dfine_hgnetv2.yml',
  '../detrv4_configs/rtv4.yml'
]

output_dir: ./outputs/rtv4_hgnetv2_l_hulunkan

# DINOv2 教师模型配置 (使用dinov2_vitb14)
teacher_model:
  type: "DINOv3TeacherModel"
  dinov3_repo_path: dinov3/
  dinov3_weights_path: pretrain/dinov3_vitb16_pretrain_lvd1689m.pth
  patch_size: 14
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

# HGNetv2 Backbone - L版本使用B4
HGNetv2:
  name: 'B4'
  return_idx: [1, 2, 3]
  freeze_stem_only: True
  freeze_at: 0
  freeze_norm: True

HybridEncoder:
  distill_teacher_dim: 768

RTv4Criterion:
  weight_dict:
    loss_distill: 15.0
  distill_adaptive_params:
    enabled: True
    rho: 2
    delta: 0.1
    default_weight: 15

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.000025
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0005
  betas: [0.9, 0.999]
  weight_decay: 0.000125

# 训练轮次 - 与其他模型保持一致 150 epochs
epoches: 150

flat_epoch: 75
no_aug_epoch: 15

train_dataloader:
  total_batch_size: 24
  dataset:
    transforms:
      policy:
        epoch: [5, 75, 135]

  collate_fn:
    mixup_epochs: [5, 75]
    stop_epoch: 135
    base_size: 1280

val_dataloader:
  total_batch_size: 16
  dataset:
    transforms:
      ops:
        - {type: Resize, size: [1280, 1280]}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}

# 输入尺寸 - 与其他模型保持一致 1280x1280
eval_spatial_size: [1280, 1280]
